/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.escuelademanejo_escritorio;
import editorTabla.ButtonEditor;
import editorTabla.ButtonRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;



/**
 *
 * @author Usuario
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        IF_autos.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        btn_autos = new javax.swing.JButton();
        btn_instructores = new javax.swing.JButton();
        btn_leccion = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        btn_administradtivos = new javax.swing.JButton();
        IF_autos = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAutosVista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        btn_autos.setBackground(new java.awt.Color(153, 255, 255));
        btn_autos.setForeground(new java.awt.Color(0, 102, 102));
        btn_autos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\icons8-auto-16.png")); // NOI18N
        btn_autos.setText("Autos");
        btn_autos.setBorderPainted(false);
        btn_autos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_autosActionPerformed(evt);
            }
        });

        btn_instructores.setBackground(new java.awt.Color(153, 255, 255));
        btn_instructores.setForeground(new java.awt.Color(0, 102, 102));
        btn_instructores.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\icons8-formación-16.png")); // NOI18N
        btn_instructores.setText("Instructores");
        btn_instructores.setBorderPainted(false);
        btn_instructores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_instructoresActionPerformed(evt);
            }
        });

        btn_leccion.setBackground(new java.awt.Color(153, 255, 255));
        btn_leccion.setForeground(new java.awt.Color(0, 102, 102));
        btn_leccion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\icons8-lección-16.png")); // NOI18N
        btn_leccion.setText("Lecciones");
        btn_leccion.setBorderPainted(false);

        btn_cliente.setBackground(new java.awt.Color(153, 255, 255));
        btn_cliente.setForeground(new java.awt.Color(0, 102, 102));
        btn_cliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\icons8-estudiante-16.png")); // NOI18N
        btn_cliente.setText("Clientes");
        btn_cliente.setBorderPainted(false);

        btn_administradtivos.setBackground(new java.awt.Color(153, 255, 255));
        btn_administradtivos.setForeground(new java.awt.Color(0, 102, 102));
        btn_administradtivos.setText("Administraativos");
        btn_administradtivos.setBorderPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_autos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_instructores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_leccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_administradtivos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btn_autos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_instructores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_leccion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_administradtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_autos.getAccessibleContext().setAccessibleName("btn_auto");

        IF_autos.setVisible(true);

        tablaAutosVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAutosVista);

        javax.swing.GroupLayout IF_autosLayout = new javax.swing.GroupLayout(IF_autos.getContentPane());
        IF_autos.getContentPane().setLayout(IF_autosLayout);
        IF_autosLayout.setHorizontalGroup(
            IF_autosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IF_autosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        IF_autosLayout.setVerticalGroup(
            IF_autosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IF_autosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IF_autos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IF_autos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(IF_autos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_autosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_autosActionPerformed
        // TODO add your handling code here:
        IF_autos.setVisible(true);
        generarDatosAutos();
    }//GEN-LAST:event_btn_autosActionPerformed

    private void btn_instructoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_instructoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_instructoresActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void ocultarventanas(){
        IF_autos.setVisible(false);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }
    
    public void generarDatosAutos() {
    String[] columnas = {"Matricula", "Modelo", "Marca", "Editar", "Eliminar"};

    Object[][] datos = {
        {"1", "1", "1", "Editar", "Eliminar"},
        {"2", "2", "2", "Editar", "Eliminar"}
    };

    DefaultTableModel modeloAutos = new DefaultTableModel(datos, columnas) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Solo las columnas 3 y 4 (Editar y Eliminar) serán editables
            return column == 3 || column == 4;
        }
    };

    tablaAutosVista.setModel(modeloAutos);

    // Renderer (botón visible)
    tablaAutosVista.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
    tablaAutosVista.getColumn("Eliminar").setCellRenderer(new ButtonRenderer("Eliminar"));

    // Editor (acción del botón)
    tablaAutosVista.getColumn("Editar").setCellEditor(
        new ButtonEditor("Editar", e -> {
            int row = Integer.parseInt(e.getActionCommand());
            String matricula = tablaAutosVista.getValueAt(row, 0).toString();

            // Abre la ventana para editar el auto
            //new VentanaEditarVehiculo(matricula).setVisible(true);
        })
    );

    tablaAutosVista.getColumn("Eliminar").setCellEditor(
        new ButtonEditor("Eliminar", e -> {
            int row = Integer.parseInt(e.getActionCommand());
            String matricula = tablaAutosVista.getValueAt(row, 0).toString();

            int r = JOptionPane.showConfirmDialog(null, 
                "¿Seguro de eliminar el auto con matrícula " + matricula + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
            );

            if (r == JOptionPane.YES_OPTION) {
                // Aquí llamas a tu DAO
                // autoDAO.eliminar(matricula);

                // Quitar de la tabla
                ((DefaultTableModel) tablaAutosVista.getModel()).removeRow(row);
            }
        })
    );
}

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame IF_autos;
    private javax.swing.JButton btn_administradtivos;
    private javax.swing.JButton btn_autos;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_instructores;
    private javax.swing.JButton btn_leccion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAutosVista;
    // End of variables declaration//GEN-END:variables
}
