/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.FunctionsDAO;
import java.awt.Window;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class IF_autos_disponibles extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_autos_disponibles
     */
    JScrollPane sp;
    public IF_autos_disponibles(JScrollPane sp) {
        initComponents();
        
        int x = new FunctionsDAO().cantidadVehiculosDisponibles();
        this.sp = sp;
        if(x==0){
            txt_cantidad_de_autos.setText("No hay vehiculos disponibles");
            txt_segerencia.setText("Se deben comprar vehiculos de repuesto o para agregar instructores");
        }else if(x<3){
            txt_cantidad_de_autos.setText("Se cuentan con " + x + " vehiculos");
            txt_segerencia.setText("Se recomienda comprar mas para agregar instructores");
        }else if(x<7){
            txt_cantidad_de_autos.setText("Se cuentan con " + x + " vehiculos");
            txt_segerencia.setText("Buena cantidad para repuesto y agregar instructores");
        }else{
            txt_cantidad_de_autos.setText("Se cuentan con " + x + " vehiculos");
            txt_segerencia.setText("La cantidad de vehiculos es por encima de la recomendada");
        }
        
        aplicarColores();
    }
    
    
    public void aplicarColores() {

    // Colores ya establecidos en el diseño general
    java.awt.Color fondo = new java.awt.Color(227, 242, 253);       // #E3F2FD
    java.awt.Color fondoControles = new java.awt.Color(207, 216, 220); // #CFD8DC
    java.awt.Color blanco = java.awt.Color.WHITE;

    // Botones
    java.awt.Color verde = new java.awt.Color(67, 160, 71);        // #43A047
    java.awt.Color grisOscuro = new java.awt.Color(84, 110, 122);  // #546E7A

    // Encabezados (si luego agregas tabla)
    java.awt.Color azulEncabezado = new java.awt.Color(25, 118, 210); // #1976D2

    // --- Aplicación de colores ---

    // Fondo general del InternalFrame
    this.getContentPane().setBackground(fondo);
    jPanel1.setBackground(fondo);

    // Textos (los fondos deben respetar el color del panel)
    txt_cantidad_de_autos.setBackground(fondo);
    txt_segerencia.setBackground(fondo);

    // Botón Ver -> Verde
    btn_ver.setBackground(verde);
    btn_ver.setForeground(blanco);

    // Botón Regresar -> Gris oscuro
    btn_regresar.setBackground(grisOscuro);
    btn_regresar.setForeground(blanco);
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_cantidad_de_autos = new javax.swing.JLabel();
        txt_segerencia = new javax.swing.JLabel();
        btn_ver = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        txt_cantidad_de_autos.setText("jLabel1");

        txt_segerencia.setText("jLabel2");

        btn_ver.setText("Ver");
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(btn_ver))
                    .addComponent(txt_segerencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cantidad_de_autos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txt_cantidad_de_autos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_segerencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ver)
                    .addComponent(btn_regresar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        // TODO add your handling code here:
        sp.removeAll();
        IF_Auto IF = new IF_Auto(false);
        sp.add(IF);
        IF.setSize(sp.getWidth(), sp.getHeight());
         IF.setVisible(true);
         Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }//GEN-LAST:event_btn_verActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_ver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_cantidad_de_autos;
    private javax.swing.JLabel txt_segerencia;
    // End of variables declaration//GEN-END:variables
}
