/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.AutoDAO;
import Modelos.Auto;
import editorTabla.ButtonEditor;
import editorTabla.ButtonRenderer;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class IF_Auto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_Auto
     */
    public IF_Auto() {
        initComponents();
        rb_matricula.setSelected(true);
        caja_asignado.removeAllItems();
        caja_asignado.addItem("TODOS");
        caja_asignado.addItem("Asignados");
        caja_asignado.addItem("Sin asignar");
        generarDatosAutos();
        aplicarColores();
    }
    
    public IF_Auto(boolean disponibles) {
        initComponents();
        rb_matricula.setSelected(true);
        caja_asignado.removeAllItems();
        caja_asignado.addItem("TODOS");
        caja_asignado.addItem("Asignados");
        caja_asignado.addItem("Sin asignar");
        
        caja_asignado.setSelectedItem("Sin asignar");
        
        generarDatosAutos();
        aplicarColores();
        
    }
    
    public void aplicarColores() {

    // Color principal de fondo
    java.awt.Color fondo = new java.awt.Color(227, 242, 253); // #E3F2FD
    java.awt.Color fondoControles = new java.awt.Color(207, 216, 220); // #CFD8DC

    // Botones
    java.awt.Color verde = new java.awt.Color(67, 160, 71);   // #43A047
    java.awt.Color grisOscuro = new java.awt.Color(84, 110, 122); // #546E7A
    java.awt.Color blanco = java.awt.Color.WHITE;

    // Tabla
    java.awt.Color encabezado = new java.awt.Color(25, 118, 210); // #1976D2

    // Fondo general
    this.getContentPane().setBackground(fondo);

    // Fondo de elementos
    rb_matricula.setBackground(fondoControles);
    rb_marca.setBackground(fondoControles);
    campo_filtro.setBackground(blanco);
    caja_asignado.setBackground(blanco);

    // Botón Nuevo
    btn_agregar.setBackground(verde);
    btn_agregar.setForeground(blanco);

    // Botón Simplificar
    btn_simplificar.setBackground(grisOscuro);
    btn_simplificar.setForeground(blanco);

    // Tabla
    tablaAutosVista.setBackground(blanco);
    tablaAutosVista.setForeground(java.awt.Color.BLACK);

    tablaAutosVista.getTableHeader().setBackground(encabezado);
    tablaAutosVista.getTableHeader().setForeground(blanco);
    tablaAutosVista.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAutosVista = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        campo_filtro = new javax.swing.JTextField();
        rb_matricula = new javax.swing.JRadioButton();
        rb_marca = new javax.swing.JRadioButton();
        txt_asignado = new javax.swing.JLabel();
        caja_asignado = new javax.swing.JComboBox<>();
        btn_simplificar = new javax.swing.JButton();
        txt_filtro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(660, 370));

        tablaAutosVista.setBackground(new java.awt.Color(153, 153, 153));
        tablaAutosVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAutosVista.setPreferredSize(new java.awt.Dimension(700, 500));
        jScrollPane1.setViewportView(tablaAutosVista);

        btn_agregar.setBackground(new java.awt.Color(0, 153, 0));
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Nuevo");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        campo_filtro.setColumns(15);
        campo_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_filtroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_filtroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_filtroKeyTyped(evt);
            }
        });

        rb_matricula.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rb_matricula);
        rb_matricula.setText("Matricula");
        rb_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_matriculaActionPerformed(evt);
            }
        });

        rb_marca.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rb_marca);
        rb_marca.setText("Marca");
        rb_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_marcaActionPerformed(evt);
            }
        });

        txt_asignado.setText("Asignado");

        caja_asignado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        caja_asignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_asignadoActionPerformed(evt);
            }
        });

        btn_simplificar.setText("Simplificar");

        txt_filtro.setText("Buscar por: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_simplificar)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_filtro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_matricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_marca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(txt_asignado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_asignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simplificar)
                            .addComponent(txt_filtro)
                            .addComponent(rb_matricula)
                            .addComponent(rb_marca)
                            .addComponent(txt_asignado)
                            .addComponent(caja_asignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        
        DialalogEdit dialogo = new DialalogEdit(
                (JFrame) SwingUtilities.getWindowAncestor(tablaAutosVista)
            );

            // Crear ventana interna para editar instructor
            IF_AgregarAuto ventana = new IF_AgregarAuto();

            dialogo.abrirInternalFrame(ventana);
            dialogo.setVisible(true);
            generarDatosAutos();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void campo_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyPressed
        // TODO add your handling code here:
        if(valido(evt.getKeyChar()))
            generarDatosAutos();
        else
            evt.consume();
    }//GEN-LAST:event_campo_filtroKeyPressed

    private void campo_filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyReleased
        // TODO add your handling code here:
        if(valido(evt.getKeyChar()))
            generarDatosAutos();
        else
            evt.consume();
    }//GEN-LAST:event_campo_filtroKeyReleased

    private void campo_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyTyped
        // TODO add your handling code here:
        if(valido(evt.getKeyChar())){
            
            generarDatosAutos();
        }else
            evt.consume();
    }//GEN-LAST:event_campo_filtroKeyTyped

    private void caja_asignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_asignadoActionPerformed
        // TODO add your handling code here:
        generarDatosAutos();
    }//GEN-LAST:event_caja_asignadoActionPerformed

    private void rb_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_marcaActionPerformed
        // TODO add your handling code here:
        generarDatosAutos();
    }//GEN-LAST:event_rb_marcaActionPerformed

    private void rb_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_matriculaActionPerformed
        // TODO add your handling code here:
        generarDatosAutos();
    }//GEN-LAST:event_rb_matriculaActionPerformed

    
    public boolean valido(char x){
        //if(campo_filtro.getText().length()<6){
            if(x<='9'&&x>='0')
                return true;
            if(x<='z'&&x>='a')
                return true;
            if(x<='z'&&x>='a')
                return true;
            
        
        //}
        if(x==8)
                return true;
        
        return false;
    }
    
    
    
    
    
    
    
    
    
    
    public void generarDatosAutos() {
        campo_filtro.setText(campo_filtro.getText().toUpperCase());
        String[] columnas = {"Matricula", "Modelo", "Marca", "Asignado","Kilometraje", "Editar", "Eliminar"};
/*
    Object[][] datos = {
        {"1", "1", "1", "Editar", "Eliminar"},
        {"2", "2", "2", "Editar", "Eliminar"}
    };
*/
    int op = caja_asignado.getSelectedIndex();
    String tipo;
    if(rb_matricula.isSelected())
        tipo = "matricula";
    else
        tipo = "marca";
    
    ArrayList<Auto> autosLista;
    if(op==0){
    autosLista = new AutoDAO().mostrarAutosFiltro(tipo, campo_filtro.getText());
    }else if(op==1){
        autosLista = new AutoDAO().mostrarAutosNoAsignadosFiltro(true,tipo, campo_filtro.getText());
    }else{
        autosLista = new AutoDAO().mostrarAutosNoAsignadosFiltro(false,tipo, campo_filtro.getText());
    }
    ArrayList<Object[]> autosParaMostrar = new ArrayList<Object[]>();
    
    for(Auto e : autosLista){
    autosParaMostrar.add(new Object[]{
        e.getMatricula(),
        e.getMarca(),
        e.getModelo(),
        e.isAsignado(),
        e.getKilometraje(),
        "Editar",
        "Eliminar"
    });
}
    
    DefaultTableModel modeloAutos = new DefaultTableModel(autosParaMostrar.toArray(new Object[0][]), columnas) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Solo las columnas 3 y 4 (Editar y Eliminar) serán editables
            return column == 5 || column == 6;
        }
    };

    tablaAutosVista.setModel(modeloAutos);

    // Renderer (botón visible)
    tablaAutosVista.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
    tablaAutosVista.getColumn("Eliminar").setCellRenderer(new ButtonRenderer("Eliminar"));

    // Editor (acción del botón)
    tablaAutosVista.getColumn("Editar").setCellEditor(
        new ButtonEditor("Editar", e -> {
            int row = Integer.parseInt(e.getActionCommand());
            String matricula = tablaAutosVista.getValueAt(row, 0).toString();

            // Abre la ventana para editar el auto
            //new VentanaEditarVehiculo(matricula).setVisible(true);
            /*
            Auto a = new Auto();
            add(new IF_EditarAuto(a).setVisible(true));
            System.out.println(matricula);
            */
             Auto a = new AutoDAO().mostrarAuto(matricula);
            DialalogEdit dialogo = new DialalogEdit((JFrame) SwingUtilities.getWindowAncestor(tablaAutosVista));

        // Crear el InternalFrame
        IF_EditarAuto editar = new IF_EditarAuto(a);

        // Abrirlo dentro del desktopPane modal
        dialogo.abrirInternalFrame(editar);
        editar.setSize(450,370);
        dialogo.setVisible(true);
        generarDatosAutos();
        })
    );

    tablaAutosVista.getColumn("Eliminar").setCellEditor(
        new ButtonEditor("Eliminar", e -> {
            int row = Integer.parseInt(e.getActionCommand());
            String matricula = tablaAutosVista.getValueAt(row, 0).toString();

            int r = JOptionPane.showConfirmDialog(null, 
                "¿Seguro de eliminar el auto con matrícula " + matricula + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
            );

            if (r == JOptionPane.YES_OPTION) {
                // Aquí llamas a tu DAO
                // autoDAO.eliminar(matricula);
                new AutoDAO().eliminarAuto(matricula);
                // Quitar de la tabla
                ((DefaultTableModel) tablaAutosVista.getModel()).removeRow(row);
                generarDatosAutos();
            }
        })
    );
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_simplificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> caja_asignado;
    private javax.swing.JTextField campo_filtro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_marca;
    private javax.swing.JRadioButton rb_matricula;
    private javax.swing.JTable tablaAutosVista;
    private javax.swing.JLabel txt_asignado;
    private javax.swing.JLabel txt_filtro;
    // End of variables declaration//GEN-END:variables
}
