/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.AutoDAO;
import Modelos.Auto;
import editorTabla.ButtonEditor;
import editorTabla.ButtonRenderer;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class IF_Auto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_Auto
     */
    public IF_Auto() {
        initComponents();
        rb_matricula.setSelected(true);
        generarDatosAutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAutosVista = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        campo_filtro = new javax.swing.JTextField();
        rb_matricula = new javax.swing.JRadioButton();
        rb_marca = new javax.swing.JRadioButton();
        txt_asignado = new javax.swing.JLabel();
        caja_asignado = new javax.swing.JComboBox<>();
        btn_simplificar = new javax.swing.JButton();
        txt_filtro = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(660, 370));

        tablaAutosVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAutosVista.setPreferredSize(new java.awt.Dimension(700, 500));
        jScrollPane1.setViewportView(tablaAutosVista);

        btn_agregar.setText("Nuevo");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        campo_filtro.setColumns(15);

        buttonGroup1.add(rb_matricula);
        rb_matricula.setText("Matricula");

        buttonGroup1.add(rb_marca);
        rb_marca.setText("Marca");

        txt_asignado.setText("Asignado");

        caja_asignado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_simplificar.setText("Simplificar");

        txt_filtro.setText("Buscar por: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_simplificar)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_filtro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_matricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_marca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(txt_asignado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_asignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simplificar)
                            .addComponent(txt_filtro)
                            .addComponent(rb_matricula)
                            .addComponent(rb_marca)
                            .addComponent(txt_asignado)
                            .addComponent(caja_asignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        
        DialalogEdit dialogo = new DialalogEdit(
                (JFrame) SwingUtilities.getWindowAncestor(tablaAutosVista)
            );

            // Crear ventana interna para editar instructor
            IF_AgregarAuto ventana = new IF_AgregarAuto();

            dialogo.abrirInternalFrame(ventana);
            dialogo.setVisible(true);
            generarDatosAutos();
    }//GEN-LAST:event_btn_agregarActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    public void generarDatosAutos() {
    String[] columnas = {"Matricula", "Modelo", "Marca", "Asignado","Kilometraje", "Editar", "Eliminar"};
/*
    Object[][] datos = {
        {"1", "1", "1", "Editar", "Eliminar"},
        {"2", "2", "2", "Editar", "Eliminar"}
    };
*/
    ArrayList<Auto> autosLista = new AutoDAO().mostrarAutos();
    
    ArrayList<Object[]> autosParaMostrar = new ArrayList<Object[]>();
    
    for(Auto e : autosLista){
    autosParaMostrar.add(new Object[]{
        e.getMatricula(),
        e.getMarca(),
        e.getModelo(),
        e.isAsignado(),
        e.getKilometraje(),
        "Editar",
        "Eliminar"
    });
}
    
    DefaultTableModel modeloAutos = new DefaultTableModel(autosParaMostrar.toArray(new Object[0][]), columnas) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Solo las columnas 3 y 4 (Editar y Eliminar) serán editables
            return column == 5 || column == 6;
        }
    };

    tablaAutosVista.setModel(modeloAutos);

    // Renderer (botón visible)
    tablaAutosVista.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
    tablaAutosVista.getColumn("Eliminar").setCellRenderer(new ButtonRenderer("Eliminar"));

    // Editor (acción del botón)
    tablaAutosVista.getColumn("Editar").setCellEditor(
        new ButtonEditor("Editar", e -> {
            int row = Integer.parseInt(e.getActionCommand());
            String matricula = tablaAutosVista.getValueAt(row, 0).toString();

            // Abre la ventana para editar el auto
            //new VentanaEditarVehiculo(matricula).setVisible(true);
            /*
            Auto a = new Auto();
            add(new IF_EditarAuto(a).setVisible(true));
            System.out.println(matricula);
            */
             Auto a = new AutoDAO().mostrarAuto(matricula);
            DialalogEdit dialogo = new DialalogEdit((JFrame) SwingUtilities.getWindowAncestor(tablaAutosVista));

        // Crear el InternalFrame
        IF_EditarAuto editar = new IF_EditarAuto(a);

        // Abrirlo dentro del desktopPane modal
        dialogo.abrirInternalFrame(editar);

        dialogo.setVisible(true);
        generarDatosAutos();
        })
    );

    tablaAutosVista.getColumn("Eliminar").setCellEditor(
        new ButtonEditor("Eliminar", e -> {
            int row = Integer.parseInt(e.getActionCommand());
            String matricula = tablaAutosVista.getValueAt(row, 0).toString();

            int r = JOptionPane.showConfirmDialog(null, 
                "¿Seguro de eliminar el auto con matrícula " + matricula + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
            );

            if (r == JOptionPane.YES_OPTION) {
                // Aquí llamas a tu DAO
                // autoDAO.eliminar(matricula);
                new AutoDAO().eliminarAuto(matricula);
                // Quitar de la tabla
                ((DefaultTableModel) tablaAutosVista.getModel()).removeRow(row);
                generarDatosAutos();
            }
        })
    );
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_simplificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> caja_asignado;
    private javax.swing.JTextField campo_filtro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_marca;
    private javax.swing.JRadioButton rb_matricula;
    private javax.swing.JTable tablaAutosVista;
    private javax.swing.JLabel txt_asignado;
    private javax.swing.JLabel txt_filtro;
    // End of variables declaration//GEN-END:variables
}
