/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Usuario
 */

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;

import Controladores.kmDAO;
import Modelos.RegistroKilometraje;
import editorTabla.ButtonEditor;
import editorTabla.ButtonRenderer;



public class IF_Corrgirkm extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_Corrgirkm
     */
    public IF_Corrgirkm() {
        initComponents();
        generarDatosKilometraje();
        aplicarColores();
    }
    
    public void aplicarColores() {

    // Colores principales
    java.awt.Color fondo = new java.awt.Color(227, 242, 253);          // #E3F2FD
    java.awt.Color fondoControles = new java.awt.Color(207, 216, 220); // #CFD8DC
    java.awt.Color blanco = java.awt.Color.WHITE;
    java.awt.Color textoNegro = java.awt.Color.BLACK;

    // Botones
    java.awt.Color grisOscuro = new java.awt.Color(84, 110, 122);      // #546E7A

    // Tabla
    java.awt.Color encabezado = new java.awt.Color(25, 118, 210);      // #1976D2

    // Fondo general
    this.getContentPane().setBackground(fondo);

    // Campo de texto
    campo_filtro.setBackground(blanco);
    campo_filtro.setForeground(textoNegro);

    // Label
    jLabel1.setForeground(textoNegro);
    jLabel1.setBackground(fondoControles);

    // Botón Cancelar
    btn_cancelar.setBackground(grisOscuro);
    btn_cancelar.setForeground(blanco);

    // Tabla
    tabla_km.setBackground(blanco);
    tabla_km.setForeground(textoNegro);

    tabla_km.getTableHeader().setBackground(encabezado);
    tabla_km.getTableHeader().setForeground(blanco);
    tabla_km.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

    // Scrollpane (opcional)
    jScrollPane2.getViewport().setBackground(blanco);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_km = new javax.swing.JTable();
        campo_filtro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();

        tabla_km.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_km);

        campo_filtro.setColumns(10);
        campo_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_filtroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_filtroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_filtroKeyTyped(evt);
            }
        });

        jLabel1.setText("Matricula del vehiculo");

        btn_cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_cancelar)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void campo_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyPressed
        // TODO add your handling code here:
        if(campo_filtro.getText().length()==6)
            if(evt.getKeyChar()!=8)
                evt.consume();
        
        generarDatosKilometraje();
    }//GEN-LAST:event_campo_filtroKeyPressed

    private void campo_filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyReleased
        // TODO add your handling code here:
        if(campo_filtro.getText().length()==6)
            if(evt.getKeyChar()!=8)
                evt.consume();
         
        
        generarDatosKilometraje();
    }//GEN-LAST:event_campo_filtroKeyReleased

    private void campo_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyTyped
        // TODO add your handling code here:
        if(campo_filtro.getText().length()==6)
            if(evt.getKeyChar()!=8)
                evt.consume();
        
        generarDatosKilometraje();
    }//GEN-LAST:event_campo_filtroKeyTyped

    
    public void generarDatosKilometraje() {
    campo_filtro.setText(campo_filtro.getText().toUpperCase());

    String[] columnas = {
        "ID", "Matrícula", "Instructor", "KM Agregados", "Fecha", "Eliminar"
    };

    kmDAO dao = new kmDAO();
    List<RegistroKilometraje> lista = dao.obtenerHistorialPorMatricula(campo_filtro.getText());

    ArrayList<Object[]> datos = new ArrayList<>();

    for (RegistroKilometraje r : lista) {
        datos.add(new Object[]{
            r.getId(),
            r.getMatricula(),
            r.getNssInstructor(),
            r.getKilometrosAgregados(),
            r.getFechaRegistro(),
            "Eliminar"
        });
    }

    DefaultTableModel modelo = new DefaultTableModel(
        datos.toArray(new Object[0][]),
        columnas
    ) {
        @Override
        public boolean isCellEditable(int row, int col) {
            return col == 5; // solo columna "Eliminar"
        }
    };

    tabla_km.setModel(modelo);

    // Renderer para mostrar el botón
    tabla_km.getColumn("Eliminar").setCellRenderer(new ButtonRenderer("Eliminar"));

    // Editor para que el botón funcione
    tabla_km.getColumn("Eliminar").setCellEditor(
        new ButtonEditor("Eliminar", e -> {
            int row = Integer.parseInt(e.getActionCommand());
            int idRegistro = Integer.parseInt(tabla_km.getValueAt(row, 0).toString());

            int r = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que deseas CORREGIR este registro?\n"
                    + "Se revertirá el kilometraje y el registro será eliminado.",
                    "Confirmar corrección",
                    JOptionPane.YES_NO_OPTION
            );

            if (r == JOptionPane.YES_OPTION) {
                kmDAO d = new kmDAO();
                boolean ok = d.corregirRegistroKilometraje(idRegistro);

                if (ok) {
                    JOptionPane.showMessageDialog(this, "Corrección realizada correctamente.");
                    generarDatosKilometraje(); 
                } else {
                    JOptionPane.showMessageDialog(this, "Error al corregir el registro.");
                }
            }
        })
    );
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JTextField campo_filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_km;
    // End of variables declaration//GEN-END:variables
}
