/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.AutoDAO;
import Modelos.Auto;
import java.awt.Window;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class IF_EditarAuto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_EditarAuto
     */
    public IF_EditarAuto() {
        initComponents();
        aplicarColores();
    }
    
    public void aplicarColores() {

    // Colores principales
    java.awt.Color fondo = new java.awt.Color(227, 242, 253);          // #E3F2FD
    java.awt.Color fondoControles = new java.awt.Color(207, 216, 220); // #CFD8DC
    java.awt.Color blanco = java.awt.Color.WHITE;
    java.awt.Color textoNegro = java.awt.Color.BLACK;

    // Botones
    java.awt.Color verde = new java.awt.Color(67, 160, 71);            // #43A047
    java.awt.Color grisOscuro = new java.awt.Color(84, 110, 122);      // #546E7A

    // Fondo general
    this.getContentPane().setBackground(fondo);

    // Campos de texto
    campo_matricula.setBackground(blanco);
    campo_marca.setBackground(blanco);
    campo_modelo.setBackground(blanco);
    campo_kilometraje.setBackground(blanco);

    campo_matricula.setForeground(textoNegro);
    campo_marca.setForeground(textoNegro);
    campo_modelo.setForeground(textoNegro);
    campo_kilometraje.setForeground(textoNegro);

    // Labels
    jLabel1.setForeground(textoNegro);
    jLabel2.setForeground(textoNegro);
    jLabel3.setForeground(textoNegro);
    jLabel4.setForeground(textoNegro);

    // Radio button
    rb_asignado.setBackground(fondoControles);
    rb_asignado.setForeground(textoNegro);

    // Botón Cancelar
    btn_cancelar.setBackground(grisOscuro);
    btn_cancelar.setForeground(blanco);

    // Botón Guardar
    btn_guardar.setBackground(verde);
    btn_guardar.setForeground(blanco);
}


    public IF_EditarAuto(Auto a) {
        initComponents();
        
        
        campo_matricula.setText(a.getMatricula());
        campo_marca.setText(a.getMarca());
        campo_modelo.setText(a.getModelo());
        campo_kilometraje.setText(""+a.getKilometraje());
        rb_asignado.setSelected(a.isAsignado());
        rb_asignado.setEnabled(false);
        aplicarColores();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo_matricula = new javax.swing.JTextField();
        campo_marca = new javax.swing.JTextField();
        campo_modelo = new javax.swing.JTextField();
        campo_kilometraje = new javax.swing.JTextField();
        rb_asignado = new javax.swing.JRadioButton();
        btn_cancelar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        campo_matricula.setEditable(false);
        campo_matricula.setColumns(10);
        campo_matricula.setText("jTextField1");

        campo_marca.setColumns(10);
        campo_marca.setText("jTextField2");

        campo_modelo.setColumns(10);
        campo_modelo.setText("jTextField3");

        campo_kilometraje.setColumns(10);
        campo_kilometraje.setText("jTextField4");

        rb_asignado.setText("Asignado");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Matricula");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Kilometraje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_guardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb_asignado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(campo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(rb_asignado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_guardar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        

    String matricula = campo_matricula.getText().trim();
    String marca = campo_marca.getText().trim();
    String modelo = campo_modelo.getText().trim();
    String kilometraje = campo_kilometraje.getText().trim();


    // Verificar campos vacíos
    if (matricula.isEmpty() || marca.isEmpty() || modelo.isEmpty() || kilometraje.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Todos los campos son obligatorios.",
            "Campos incompletos",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Verificar que el kilometraje sea numérico
    try {
        int km = Integer.parseInt(kilometraje);
        if (km < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El kilometraje no puede ser negativo.",
                "Dato inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El kilometraje debe ser un número válido.",
            "Formato inválido",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    Auto auto = new Auto(
        matricula,
        false,      
        marca,
        modelo,
        kilometraje
    );
    
    new AutoDAO().editarAuto(auto);
    
    Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }
    }//GEN-LAST:event_btn_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JTextField campo_kilometraje;
    private javax.swing.JTextField campo_marca;
    private javax.swing.JTextField campo_matricula;
    private javax.swing.JTextField campo_modelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rb_asignado;
    // End of variables declaration//GEN-END:variables
}
