/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.AutoDAO;
import Modelos.Auto;
import Modelos.Instructor;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class IF_EditarInstructor extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_EditarInstructor
     */
    public IF_EditarInstructor() {
        initComponents();
    }

    public IF_EditarInstructor(Instructor ins) {
        initComponents();
        
        campo_nss.setText(ins.getNSS());
    campo_nombre.setText(ins.getNombre());
    campo_apellidoPat.setText(ins.getApellidoPat());
    campo_apellidoMat.setText(ins.getApellidoMat());

    // Checkbox / Radio senior
    rb_senior.setSelected(ins.isSenior());
    
        cargarAutosNoAsignados(ins.getMatriculaVehiculo());
        
    }
    
    
    private void cargarAutosNoAsignados(String matricula) {

    AutoDAO autoDAO = new AutoDAO();
    ArrayList<Auto> autos = autoDAO.mostrarAutosNoAsignados(false);

    
    
    caja_autosDisponibles.removeAllItems(); // Limpia el combo

    caja_autosDisponibles.addItem(matricula); // Opcional

    for (Auto auto : autos) {
        caja_autosDisponibles.addItem(auto.getMatricula());
    }
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cancelar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        rb_senior = new javax.swing.JRadioButton();
        campo_nss = new javax.swing.JTextField();
        campo_nombre = new javax.swing.JTextField();
        campo_apellidoPat = new javax.swing.JTextField();
        campo_apellidoMat = new javax.swing.JTextField();
        caja_autosDisponibles = new javax.swing.JComboBox<>();
        txt_nss = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        txt_apellidoPat = new javax.swing.JLabel();
        txt_apellidoMat = new javax.swing.JLabel();
        txt_vehiculo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(530, 310));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        rb_senior.setText("Senior");

        campo_nss.setEditable(false);
        campo_nss.setColumns(10);
        campo_nss.setText("jTextField1");

        campo_nombre.setColumns(10);
        campo_nombre.setText("jTextField2");

        campo_apellidoPat.setColumns(10);
        campo_apellidoPat.setText("jTextField3");

        campo_apellidoMat.setColumns(10);
        campo_apellidoMat.setText("jTextField4");

        caja_autosDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_nss.setText("NSS");

        txt_nombre.setText("Nombre");

        txt_apellidoPat.setText("Apellido paterno");

        txt_apellidoMat.setText("Apellido materno");

        txt_vehiculo.setText("Vehiculo asignado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre)
                            .addComponent(txt_nss)
                            .addComponent(txt_apellidoPat)
                            .addComponent(txt_apellidoMat)
                            .addComponent(txt_vehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_nss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_apellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_apellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja_autosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb_senior)
                        .addGap(112, 112, 112)
                        .addComponent(btn_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(btn_guardar)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campo_nss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nss))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre))
                                .addGap(18, 18, 18)
                                .addComponent(campo_apellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_apellidoPat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo_apellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_apellidoMat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caja_autosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vehiculo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_senior)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancelar)
                            .addComponent(btn_guardar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        
 
        Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> caja_autosDisponibles;
    private javax.swing.JTextField campo_apellidoMat;
    private javax.swing.JTextField campo_apellidoPat;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_nss;
    private javax.swing.JRadioButton rb_senior;
    private javax.swing.JLabel txt_apellidoMat;
    private javax.swing.JLabel txt_apellidoPat;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_nss;
    private javax.swing.JLabel txt_vehiculo;
    // End of variables declaration//GEN-END:variables
}
