/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.HistorialDAO;
import Controladores.InstructorDAO;
import Generar.generar_pdf;
import Modelos.Historial;
import Modelos.Instructor;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class IF_filtro_documento extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_filtro_documento
     */
    public IF_filtro_documento() {
        initComponents();
        filtro_ins.removeAllItems();
        filtro_ins.addItem("TODOS");
        ArrayList<Instructor> list = new InstructorDAO().mostrarInstructores();
        
        for( Instructor i : list){
            filtro_ins.addItem(i.getNSS() + " " + i.getNombre());
        }
        aplicarColores();
    }
    
    private void aplicarColores() {
    // Colores principales
    java.awt.Color fondo = new java.awt.Color(227, 242, 253);        // #E3F2FD
    java.awt.Color fondoControles = new java.awt.Color(207, 216, 220); // #CFD8DC
    java.awt.Color blanco = java.awt.Color.WHITE;

    // Botones
    java.awt.Color verde = new java.awt.Color(67, 160, 71);         // #43A047
    java.awt.Color grisOscuro = new java.awt.Color(84, 110, 122);   // #546E7A

    // Fondo del frame
    getContentPane().setBackground(fondo);

    // Label
    jLabel1.setForeground(grisOscuro);
    jLabel1.setBackground(fondo);

    // ComboBox
    filtro_ins.setBackground(blanco);
    filtro_ins.setForeground(java.awt.Color.BLACK);

    // Botones
    btn_generar_reporte.setBackground(verde);
    btn_generar_reporte.setForeground(blanco);
    btn_generar_reporte.setFocusPainted(false);

    btn_cancelar.setBackground(grisOscuro);
    btn_cancelar.setForeground(blanco);
    btn_cancelar.setFocusPainted(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filtro_ins = new javax.swing.JComboBox<>();
        btn_generar_reporte = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        jLabel1.setText("Instructor del que sera el reporte");

        filtro_ins.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_generar_reporte.setText("Generar");
        btn_generar_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generar_reporteActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtro_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_generar_reporte)
                    .addComponent(btn_cancelar))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_cancelar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtro_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generar_reporte))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generar_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generar_reporteActionPerformed
        // TODO add your handling code here:
        String op = (String) filtro_ins.getSelectedItem();
        if(op.equals("TODOS")){
            List<Historial> lista = new HistorialDAO().obtenerHistorialCompleto();

            generar_pdf.generarHistorialPDF(lista, "historial.pdf");

            JOptionPane.showMessageDialog(this, "Reporte generado: historial.pdf");

        
            try {
                java.awt.Desktop.getDesktop().open(new java.io.File("historial.pdf"));
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }else{
            String separacion[] = op.split(" ");
            
            List<Historial> lista = new HistorialDAO().obtenerHistorialFiltrado(separacion[0]);

            generar_pdf.generarHistorialPDF(lista, "historial.pdf");

            JOptionPane.showMessageDialog(this, "Reporte generado: historial.pdf");

        
            try {
                java.awt.Desktop.getDesktop().open(new java.io.File("historial.pdf"));
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_btn_generar_reporteActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }
    }//GEN-LAST:event_btn_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_generar_reporte;
    private javax.swing.JComboBox<String> filtro_ins;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
