/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.InstructorDAO;
import Modelos.Instructor;
import editorTabla.ButtonEditor;
import editorTabla.ButtonRenderer;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class IF_Instructor extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_Instructor
     */
    public IF_Instructor() {
        
        initComponents();
        
        generarDatosInstructores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInstructoresVista = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(660, 425));

        tablaInstructoresVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInstructoresVista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    public void generarDatosInstructores() {

    String[] columnas = {"NSS", "Nombre", "Apellido P.", "Apellido M.", "Senior", "Vehículo", "Editar", "Eliminar"};

    // Datos de prueba (puedes cambiarlo luego por tu DAO)
    Object[][] datos = {
        {"123", "Juan", "Pérez", "López", true, "ABC-123", "Editar", "Eliminar"},
        {"456", "María", "García", "Torres", false, "XYZ-789", "Editar", "Eliminar"}
    };
    
    ArrayList<Instructor> instructoresLista = new InstructorDAO().mostrarInstructores();
    
    ArrayList<Object[]> instructoresParaMostrar = new ArrayList<Object[]>();
    
    for(Instructor e : instructoresLista){
    instructoresParaMostrar.add(new Object[]{
        e.getNSS(),
        e.getNombre(),
        e.getApellidoPat(),
        e.getApellidoMat(),
        e.isSenior(),
        e.getMatriculaVehiculo(),
        "Editar",
        "Eliminar"
    });
}
    
    
    
    
    
    
    
    

    DefaultTableModel modeloInstructores = new DefaultTableModel(instructoresParaMostrar.toArray(new Object[0][]), columnas) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 6 || column == 7;  // Solo Editar y Eliminar
        }
    };

    tablaInstructoresVista.setModel(modeloInstructores);

    // Renderers de botones
    tablaInstructoresVista.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
    tablaInstructoresVista.getColumn("Eliminar").setCellRenderer(new ButtonRenderer("Eliminar"));


    // -------------------------
    // BOTÓN EDITAR
    // -------------------------
    tablaInstructoresVista.getColumn("Editar").setCellEditor(
        new ButtonEditor("Editar", e -> {

            int row = Integer.parseInt(e.getActionCommand());
            String NSS = tablaInstructoresVista.getValueAt(row, 0).toString();
            
            // Obtener datos del instructor seleccionado
            Instructor ins = new InstructorDAO().mostrarInstructor(NSS);
            

            // Crear el dialogo modal
            DialalogEdit dialogo = new DialalogEdit(
                (JFrame) SwingUtilities.getWindowAncestor(tablaInstructoresVista)
            );

            // Crear ventana interna para editar instructor
            IF_EditarInstructor ventana = new IF_EditarInstructor(ins);

            dialogo.abrirInternalFrame(ventana);
            dialogo.setVisible(true);
        })
    );



    // -------------------------
    // BOTÓN ELIMINAR
    // -------------------------
    tablaInstructoresVista.getColumn("Eliminar").setCellEditor(
        new ButtonEditor("Eliminar", e -> {

            int row = Integer.parseInt(e.getActionCommand());
            String nss = tablaInstructoresVista.getValueAt(row, 0).toString();

            int r = JOptionPane.showConfirmDialog(null,
                    "¿Seguro de eliminar al instructor con NSS " + nss + "?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (r == JOptionPane.YES_OPTION) {

                // Aquí llamas a tu DAO si lo usas (ejemplo):
                // instructorDAO.eliminar(nss);

                ((DefaultTableModel) tablaInstructoresVista.getModel()).removeRow(row);
            }
        })
    );
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInstructoresVista;
    // End of variables declaration//GEN-END:variables
}
