/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.AutoDAO;
import Controladores.InstructorDAO;
import Modelos.Instructor;
import editorTabla.ButtonEditor;
import editorTabla.ButtonRenderer;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class IF_Instructor extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_Instructor
     */
    public IF_Instructor() {
        
        initComponents();
        
        rb_NSS.setSelected(true);
        generarDatosInstructores();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInstructoresVista = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        campo_busqueda = new javax.swing.JTextField();
        txt_campoBusqueda = new javax.swing.JLabel();
        btn_simplificar = new javax.swing.JButton();
        rb_NSS = new javax.swing.JRadioButton();
        rb_nombre = new javax.swing.JRadioButton();
        caja_senior = new javax.swing.JComboBox<>();
        txt_senior = new javax.swing.JLabel();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(660, 370));
        setPreferredSize(new java.awt.Dimension(660, 370));

        tablaInstructoresVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInstructoresVista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaInstructoresVistaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInstructoresVista);

        btn_agregar.setText("Nuevo");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        campo_busqueda.setColumns(20);
        campo_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_busquedaActionPerformed(evt);
            }
        });
        campo_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_busquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_busquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_busquedaKeyTyped(evt);
            }
        });

        txt_campoBusqueda.setText("Buscar por: ");

        btn_simplificar.setText("Simplificar");

        buttonGroup1.add(rb_NSS);
        rb_NSS.setText("NSS");

        buttonGroup1.add(rb_nombre);
        rb_nombre.setText("Nombre");

        caja_senior.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_senior.setText("Senior");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_simplificar)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_campoBusqueda)
                        .addGap(18, 18, 18)
                        .addComponent(rb_NSS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_nombre)
                        .addGap(18, 18, 18)
                        .addComponent(txt_senior)
                        .addGap(18, 18, 18)
                        .addComponent(caja_senior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(campo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_simplificar)
                                    .addComponent(txt_campoBusqueda)
                                    .addComponent(rb_NSS)
                                    .addComponent(rb_nombre)
                                    .addComponent(txt_senior)
                                    .addComponent(caja_senior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        
        //if(true){
        if(new AutoDAO().mostrarAutos().isEmpty()){
        JOptionPane.showMessageDialog(this, "No hay vahiculos disponibles para nuevos instructores\nAgrega vehiculos para asignar a instructores nuevos");
        }else{
        DialalogEdit dialogo = new DialalogEdit(
                (JFrame) SwingUtilities.getWindowAncestor(tablaInstructoresVista)
            );

            // Crear ventana interna para editar instructor
            IF_AgregarInstructor ventana = new IF_AgregarInstructor();

            dialogo.abrirInternalFrame(ventana);
            dialogo.setVisible(true);
                }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void campo_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_busquedaActionPerformed

    private void campo_busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_busquedaKeyReleased
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if(!esNumero(x)||campo_busqueda.getText().length()>=10){
            if(x!=8)
                evt.consume();
        }else{
            generarDatosInstructores();
        }
    }//GEN-LAST:event_campo_busquedaKeyReleased

    private void campo_busquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_busquedaKeyPressed
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if(!esNumero(x)||campo_busqueda.getText().length()>=10){
            if(x!=8)
                evt.consume();
        }else{
            generarDatosInstructores();
        }
    }//GEN-LAST:event_campo_busquedaKeyPressed

    private void campo_busquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_busquedaKeyTyped
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if(!esNumero(x)||campo_busqueda.getText().length()>=10){
            if(x!=8)
                evt.consume();
            else
                generarDatosInstructores();
        }else{
            generarDatosInstructores();
        }
    }//GEN-LAST:event_campo_busquedaKeyTyped

    private void tablaInstructoresVistaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInstructoresVistaMouseReleased
        // TODO add your handling code here:
        //String a = (String) tablaInstructoresVista.getValueAt(, 0)
    }//GEN-LAST:event_tablaInstructoresVistaMouseReleased

    private boolean esNumero(char a){
        if((a>='0'&&a<='9'))
            return true;
        else
            return false;
    }
    
    
    public void generarDatosInstructores() {

    String[] columnas = {"NSS", "Nombre", "Apellido P.", "Apellido M.", "Senior", "Vehículo", "Editar", "Eliminar"};
/*
    Object[][] datos = {
        {"123", "Juan", "Pérez", "López", true, "ABC-123", "Editar", "Eliminar"},
        {"456", "María", "García", "Torres", false, "XYZ-789", "Editar", "Eliminar"}
    };*/
    
    ArrayList<Instructor> instructoresLista = new InstructorDAO().mostrarInstructoresFiltro(campo_busqueda.getText());
    
    ArrayList<Object[]> instructoresParaMostrar = new ArrayList<Object[]>();
    
    for(Instructor e : instructoresLista){
    instructoresParaMostrar.add(new Object[]{
        e.getNSS(),
        e.getNombre(),
        e.getApellidoPat(),
        e.getApellidoMat(),
        e.isSenior(),
        e.getMatriculaVehiculo(),
        "Editar",
        "Eliminar"
    });
}
    
    
    
    
    
    
    
    

    DefaultTableModel modeloInstructores = new DefaultTableModel(instructoresParaMostrar.toArray(new Object[0][]), columnas) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 6 || column == 7;  // Solo Editar y Eliminar
        }
    };

    tablaInstructoresVista.setModel(modeloInstructores);

    // Renderers de botones
    tablaInstructoresVista.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
    tablaInstructoresVista.getColumn("Eliminar").setCellRenderer(new ButtonRenderer("Eliminar"));


    // -------------------------
    // BOTÓN EDITAR
    // -------------------------
    tablaInstructoresVista.getColumn("Editar").setCellEditor(
        new ButtonEditor("Editar", e -> {

            int row = Integer.parseInt(e.getActionCommand());
            String NSS = tablaInstructoresVista.getValueAt(row, 0).toString();
            
            // Obtener datos del instructor seleccionado
            Instructor ins = new InstructorDAO().mostrarInstructor(NSS);
            

            // Crear el dialogo modal
            DialalogEdit dialogo = new DialalogEdit(
                (JFrame) SwingUtilities.getWindowAncestor(tablaInstructoresVista)
            );

            // Crear ventana interna para editar instructor
            IF_EditarInstructor ventana = new IF_EditarInstructor(ins);

            dialogo.abrirInternalFrame(ventana);
            dialogo.setVisible(true);
        })
    );



    // -------------------------
    // BOTÓN ELIMINAR
    // -------------------------
    tablaInstructoresVista.getColumn("Eliminar").setCellEditor(
        new ButtonEditor("Eliminar", e -> {

            int row = Integer.parseInt(e.getActionCommand());
            String nss = tablaInstructoresVista.getValueAt(row, 0).toString();

            int r = JOptionPane.showConfirmDialog(null,
                    "¿Seguro de eliminar al instructor con NSS " + nss + "?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (r == JOptionPane.YES_OPTION) {

                new InstructorDAO().eliminarInstructor(nss);
                generarDatosInstructores();
            }
        })
    );
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_simplificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> caja_senior;
    private javax.swing.JTextField campo_busqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_NSS;
    private javax.swing.JRadioButton rb_nombre;
    private javax.swing.JTable tablaInstructoresVista;
    private javax.swing.JLabel txt_campoBusqueda;
    private javax.swing.JLabel txt_senior;
    // End of variables declaration//GEN-END:variables
}
