/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.InstructorDAO;
import Controladores.ProceduresDAO;
import Modelos.Instructor;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class IF_intercambio_auto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_intercambio_auto
     */
    public IF_intercambio_auto() {
        initComponents();
        generarTablaInstructores('A');
        generarTablaInstructores('B');
        nombre_A.setEditable(false);
        nombre_B.setEditable(false);
        matricula_A.setEditable(false);
        matricula_B.setEditable(false);
        
        btn_intercambiar.setEnabled(false);
        
        
    }
    
    
    
    public boolean validarCaracter(char a){
        if(a==8)
            return true;
        else if(a>='0' && a<='9')
            return true;
        else
            return false;
    }
    
    
    public void generarTablaInstructores(char tabla) {
        
        
        ArrayList<Instructor> lista = new InstructorDAO().mostrarInstructores();
        if(tabla == 'A')
            lista = new InstructorDAO().mostrarInstructoresFiltro(NSS_A.getText());
        else if(tabla == 'B')
            lista = new InstructorDAO().mostrarInstructoresFiltro(NSS_B.getText());

    String[] columnas = {"NSS", "Nombre", "Apellido P.", "Apellido M.","Vehículo"};

        ArrayList<Object[]> datos = new ArrayList<>();

    for (Instructor ins : lista) {

        datos.add(new Object[]{
            ins.getNSS(),
            ins.getNombre(),
            ins.getApellidoPat(),
            ins.getApellidoMat(),
            ins.getMatriculaVehiculo()
        });
    }

        DefaultTableModel modelo = new DefaultTableModel(
        datos.toArray(new Object[0][]),
        columnas
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Celdas no editables
        }
    };

        llenarCampos(tabla);
        System.out.println("NSS: " + NSS_A.getText());
        
    // ===============================
    //  SELECCIONAR LA TABLA SEGÚN 'tabla'
    // ===============================
    if (tabla == 'A') {
        
        tabla_instructores_A.setModel(modelo);
        tabla_instructores_A.setRowHeight(25);
    }
    else if (tabla == 'B') {
        tabla_instructores_B.setModel(modelo);
        tabla_instructores_B.setRowHeight(25);
    }
    if(matricula_A.getText().isEmpty() || matricula_B.getText().isEmpty())
        btn_intercambiar.setEnabled(false);
    else 
        btn_intercambiar.setEnabled(true);
}
    
   public void llenarCampos(char tabla){
       if(tabla == 'A'){
           Instructor ins = new InstructorDAO().mostrarInstructor(NSS_A.getText());
           
           if(ins==null){
               nombre_A.setText("");
               matricula_A.setText("");
           }else{
               nombre_A.setText(ins.getNombre());
               matricula_A.setText(ins.getMatriculaVehiculo());
           }
           
       }else if(tabla == 'B'){
           Instructor ins = new InstructorDAO().mostrarInstructor(NSS_B.getText());
           
           if(ins==null){
               nombre_B.setText("");
               matricula_B.setText("");
           }else{
               nombre_B.setText(ins.getNombre());
               matricula_B.setText(ins.getMatriculaVehiculo());
           }
       }
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NSS_A = new javax.swing.JTextField();
        NSS_B = new javax.swing.JTextField();
        nombre_B = new javax.swing.JTextField();
        nombre_A = new javax.swing.JTextField();
        matricula_B = new javax.swing.JTextField();
        matricula_A = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_instructores_B = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_instructores_A = new javax.swing.JTable();
        btn_cancelar = new javax.swing.JButton();
        btn_intercambiar = new javax.swing.JButton();
        txt_NSS = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JLabel();

        NSS_A.setColumns(10);
        NSS_A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NSS_AKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NSS_AKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NSS_AKeyTyped(evt);
            }
        });

        NSS_B.setColumns(10);
        NSS_B.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NSS_BKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NSS_BKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NSS_BKeyTyped(evt);
            }
        });

        nombre_B.setColumns(10);

        nombre_A.setColumns(10);

        matricula_B.setColumns(10);

        matricula_A.setColumns(10);

        tabla_instructores_B.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_instructores_B);

        tabla_instructores_A.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_instructores_A);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_intercambiar.setText("Intercambiar");
        btn_intercambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_intercambiarActionPerformed(evt);
            }
        });

        txt_NSS.setText("NSS");

        txt_nombre.setText("Nombre");

        txt_matricula.setText("Matricula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NSS_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matricula_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_matricula)
                            .addComponent(txt_nombre))
                        .addGap(195, 195, 195))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(txt_NSS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NSS_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matricula_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btn_cancelar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_intercambiar)
                        .addGap(158, 158, 158))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NSS_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NSS_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NSS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricula_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matricula_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matricula))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_intercambiar))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NSS_AKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NSS_AKeyPressed
        // TODO add your handling code here:
        if(validarCaracter(evt.getKeyChar())&&NSS_A.getText().length()<11){
            
        }else
            if(evt.getKeyChar()!=8)
                evt.consume();
        
        generarTablaInstructores('A');
    }//GEN-LAST:event_NSS_AKeyPressed

    private void NSS_AKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NSS_AKeyReleased
        // TODO add your handling code here:
        if(validarCaracter(evt.getKeyChar())&&NSS_A.getText().length()<11){
            
        }else
            if(evt.getKeyChar()!=8)
                evt.consume();
        
        generarTablaInstructores('A');
    }//GEN-LAST:event_NSS_AKeyReleased

    private void NSS_AKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NSS_AKeyTyped
        // TODO add your handling code here:
        if(validarCaracter(evt.getKeyChar())&&NSS_A.getText().length()<11){
            
        }else
            if(evt.getKeyChar()!=8)
                evt.consume();
        
        generarTablaInstructores('A');
    }//GEN-LAST:event_NSS_AKeyTyped

    private void NSS_BKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NSS_BKeyPressed
        // TODO add your handling code here:
        if(validarCaracter(evt.getKeyChar())&&NSS_B.getText().length()<11){
            
        }else
            if(evt.getKeyChar()!=8)
                evt.consume();
        
        generarTablaInstructores('B');
    }//GEN-LAST:event_NSS_BKeyPressed

    private void NSS_BKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NSS_BKeyReleased
        // TODO add your handling code here:
        if(validarCaracter(evt.getKeyChar())&&NSS_B.getText().length()<11){
            
        }else
            if(evt.getKeyChar()!=8)
                evt.consume();
        
        generarTablaInstructores('B');
    }//GEN-LAST:event_NSS_BKeyReleased

    private void NSS_BKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NSS_BKeyTyped
        // TODO add your handling code here:
        if(validarCaracter(evt.getKeyChar())&&NSS_B.getText().length()<11){
            
        }else
            if(evt.getKeyChar()!=8)
                evt.consume();
        
        generarTablaInstructores('B');
    }//GEN-LAST:event_NSS_BKeyTyped

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_intercambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_intercambiarActionPerformed
        // TODO add your handling code here:
        if(NSS_A.getText().equals(NSS_B.getText())){
            JOptionPane.showMessageDialog(
                this,
                "Los NSS no pueden ser iguales.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
        else{
            new ProceduresDAO().intercambiarAutos(NSS_A.getText(), NSS_B.getText());
            generarTablaInstructores('A');
            generarTablaInstructores('B');
        }
    }//GEN-LAST:event_btn_intercambiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NSS_A;
    private javax.swing.JTextField NSS_B;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_intercambiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField matricula_A;
    private javax.swing.JTextField matricula_B;
    private javax.swing.JTextField nombre_A;
    private javax.swing.JTextField nombre_B;
    private javax.swing.JTable tabla_instructores_A;
    private javax.swing.JTable tabla_instructores_B;
    private javax.swing.JLabel txt_NSS;
    private javax.swing.JLabel txt_matricula;
    private javax.swing.JLabel txt_nombre;
    // End of variables declaration//GEN-END:variables
}
