/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import javax.swing.JDesktopPane;
import javax.swing.JScrollPane;
import javax.swing.plaf.DesktopPaneUI;

/**
 *
 * @author Usuario
 */
public class IF_inicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_inicio
     */
    
    JScrollPane sp;
    public IF_inicio(JScrollPane sp) {
        initComponents();
        this.sp = sp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_view_instructor_auto = new javax.swing.JButton();
        view_historial_instructor = new javax.swing.JButton();
        btn_procedure_aumento_km = new javax.swing.JButton();
        btn_procedure_intercambio = new javax.swing.JButton();
        btn_function_autos_disponibles = new javax.swing.JButton();
        btn_function_encontrar_instructor = new javax.swing.JButton();
        btn_generar_documento = new javax.swing.JButton();
        btn_grafica = new javax.swing.JButton();

        btn_view_instructor_auto.setText("Instructores y sus autos");
        btn_view_instructor_auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_instructor_autoActionPerformed(evt);
            }
        });

        view_historial_instructor.setText("Historial de autos usados");
        view_historial_instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_historial_instructorActionPerformed(evt);
            }
        });

        btn_procedure_aumento_km.setText("jButton3");

        btn_procedure_intercambio.setText("jButton4");
        btn_procedure_intercambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procedure_intercambioActionPerformed(evt);
            }
        });

        btn_function_autos_disponibles.setText("jButton5");

        btn_function_encontrar_instructor.setText("jButton6");

        btn_generar_documento.setText("jButton7");

        btn_grafica.setText("jButton8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btn_generar_documento)
                        .addGap(174, 174, 174)
                        .addComponent(btn_grafica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(view_historial_instructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_view_instructor_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_procedure_intercambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_procedure_aumento_km, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_function_autos_disponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_function_encontrar_instructor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_procedure_aumento_km)
                    .addComponent(btn_function_autos_disponibles)
                    .addComponent(btn_view_instructor_auto))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_historial_instructor)
                    .addComponent(btn_procedure_intercambio)
                    .addComponent(btn_function_encontrar_instructor))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_grafica)
                    .addComponent(btn_generar_documento))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_procedure_intercambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procedure_intercambioActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btn_procedure_intercambioActionPerformed

    private void btn_view_instructor_autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_instructor_autoActionPerformed
        // TODO add your handling code here:
        IF_view_instructor_auto IF = new IF_view_instructor_auto(sp);
        sp.add(IF);
        IF.setSize(sp.getWidth(), sp.getHeight());
         IF.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_view_instructor_autoActionPerformed

    private void view_historial_instructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_historial_instructorActionPerformed
        // TODO add your handling code here:
        IF_view_historial IF = new IF_view_historial(sp);
        sp.add(IF);
        IF.setSize(sp.getWidth(), sp.getHeight());
         IF.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_view_historial_instructorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_function_autos_disponibles;
    private javax.swing.JButton btn_function_encontrar_instructor;
    private javax.swing.JButton btn_generar_documento;
    private javax.swing.JButton btn_grafica;
    private javax.swing.JButton btn_procedure_aumento_km;
    private javax.swing.JButton btn_procedure_intercambio;
    private javax.swing.JButton btn_view_instructor_auto;
    private javax.swing.JButton view_historial_instructor;
    // End of variables declaration//GEN-END:variables
}
