/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Usuario
 */
public class IF_NoDisponible extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_NoDisponible
     */
    public IF_NoDisponible() {
        initComponents();
        aplicarColoresNT();
    }
    public void aplicarColoresNT() {
        java.awt.Color crema = new java.awt.Color(255, 252, 245);

        // Fondo verdadero del InternalFrame
        this.getContentPane().setBackground(crema);

        // Fondo del icono
        NT_Icon.setBackground(crema);
        NT_Icon.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NT_Icon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        NT_Icon.setBackground(new java.awt.Color(255, 252, 245));
        NT_Icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\NT_image-convertido-a-300x370.jpeg")); // NOI18N
        NT_Icon.setPreferredSize(new java.awt.Dimension(630, 425));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(NT_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(563, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NT_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NT_Icon;
    // End of variables declaration//GEN-END:variables
}
