/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.AutoDAO;
import Controladores.FunctionsDAO;
import Modelos.Auto;
import Modelos.Instructor;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class IF_responsable_de_auto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_responsable_de_auto
     */
    public IF_responsable_de_auto() {
        initComponents();
        generarDatosAutos();
        aplicarColores();
    }
    
    private void aplicarColores() {

    // Colores principales
    java.awt.Color fondo = new java.awt.Color(227, 242, 253);        // #E3F2FD
    java.awt.Color fondoControles = new java.awt.Color(207, 216, 220); // #CFD8DC
    java.awt.Color blanco = java.awt.Color.WHITE;

    // Botones
    java.awt.Color verde = new java.awt.Color(67, 160, 71);         // #43A047
    java.awt.Color grisOscuro = new java.awt.Color(84, 110, 122);   // #546E7A

    // Tabla
    java.awt.Color azulEncabezado = new java.awt.Color(25, 118, 210); // #1976D2

    // -----------------------------
    //        APLICAR COLORES
    // -----------------------------

    // Fondo general
    getContentPane().setBackground(fondo);

    // Etiquetas
    txt_matricula.setForeground(java.awt.Color.BLACK);

    // Campo de texto
    campo_filtro.setBackground(blanco);
    campo_filtro.setForeground(java.awt.Color.BLACK);
    campo_filtro.setCaretColor(java.awt.Color.BLACK);

    // Botón Buscar
    btn_buscar.setBackground(verde);
    btn_buscar.setForeground(blanco);
    btn_buscar.setFocusPainted(false);

    // Botón Regresar
    btn_regresar.setBackground(grisOscuro);
    btn_regresar.setForeground(blanco);
    btn_regresar.setFocusPainted(false);

    // Tabla
    tabla_autos.setBackground(blanco);
    tabla_autos.setForeground(java.awt.Color.BLACK);
    tabla_autos.setRowHeight(25);

    // Encabezado tabla
    tabla_autos.getTableHeader().setBackground(azulEncabezado);
    tabla_autos.getTableHeader().setForeground(blanco);
    tabla_autos.getTableHeader().setOpaque(true);
    tabla_autos.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

    // Alternancia de filas
    tabla_autos.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            java.awt.Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            if (!isSelected) {
                if (row % 2 == 0) {
                    c.setBackground(fondo);
                } else {
                    c.setBackground(fondoControles);
                }
                c.setForeground(java.awt.Color.BLACK);
            } else {
                c.setBackground(verde);
                c.setForeground(blanco);
            }

            return c;
        }
    });
}


    
    
    public void generarDatosAutos() {
    campo_filtro.setText(campo_filtro.getText().toUpperCase());

    // Solo estas columnas
    String[] columnas = {"Matricula", "Marca", "Modelo", "Kilometraje"};

    String tipo ="matricula";

    ArrayList<Auto> autosLista;

        autosLista = new AutoDAO().mostrarAutosFiltro(tipo, campo_filtro.getText());

        ArrayList<Object[]> autosParaMostrar = new ArrayList<>();

    for (Auto e : autosLista) {
        autosParaMostrar.add(new Object[]{
            e.getMatricula(),
            e.getMarca(),
            e.getModelo(),
            e.getKilometraje()
        });
    }

    DefaultTableModel modeloAutos = new DefaultTableModel(
        autosParaMostrar.toArray(new Object[0][]),
        columnas
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Ya no hay botones, todo es NO editable
        }
    };

    tabla_autos.setModel(modeloAutos);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_autos = new javax.swing.JTable();
        campo_filtro = new javax.swing.JTextField();
        txt_matricula = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        tabla_autos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_autos);

        campo_filtro.setColumns(10);
        campo_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_filtroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_filtroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_filtroKeyTyped(evt);
            }
        });

        txt_matricula.setText("Matricula");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresar)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_matricula)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_buscar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_matricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyPressed
        // TODO add your handling code here:
        if(campo_filtro.getText().length()<6){
            
        }else
            evt.consume();
        
        generarDatosAutos();
    }//GEN-LAST:event_campo_filtroKeyPressed

    private void campo_filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyReleased
        // TODO add your handling code here:
        if(campo_filtro.getText().length()<6){
            
        }else
            evt.consume();
        
        generarDatosAutos();
    }//GEN-LAST:event_campo_filtroKeyReleased

    private void campo_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyTyped
        // TODO add your handling code here:
        if(campo_filtro.getText().length()<6){
            
        }else
            evt.consume();
        
        generarDatosAutos();
    }//GEN-LAST:event_campo_filtroKeyTyped

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        String matricula = campo_filtro.getText().trim().toUpperCase();

    if (matricula.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese una matrícula para buscar.");
        return;
    }

    // 1. Buscar auto
    Auto auto = new AutoDAO().mostrarAuto(matricula);

    if (auto == null) {
        JOptionPane.showMessageDialog(this, 
            "No existe un vehículo con matrícula: " + matricula,
            "Vehículo no encontrado",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // 2. Existe pero NO está asignado
    if (!auto.isAsignado()) {
        JOptionPane.showMessageDialog(this, 
            "El vehículo " + matricula + " existe pero NO está asignado a ningún instructor.",
            "Vehículo sin asignación",
            JOptionPane.INFORMATION_MESSAGE
        );
        return;
    }
        Instructor inst = new FunctionsDAO().instructorAsignadoPorMatricula(matricula);


    // 3. Si encontró instructor → mostrar datos
    String mensaje = 
        "Instructor asignado:\n" +
        "Nombre: " + inst.getNombre() + " " + inst.getApellidoPat() + " " + inst.getApellidoMat() + "\n\n" +
        "Cualquier problema con el vehículo, contacte a este instructor.";

    JOptionPane.showMessageDialog(this, mensaje, 
            "Vehículo asignado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JTextField campo_filtro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_autos;
    private javax.swing.JLabel txt_matricula;
    // End of variables declaration//GEN-END:variables
}
