/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.AutoDAO;
import Controladores.InstructorDAO;
import Controladores.ProceduresDAO;
import Modelos.Auto;
import Modelos.Instructor;
import java.awt.Dimension;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JSpinner;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class IF_registrar_aumento_km extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_registrar_aumento_km
     */
    public IF_registrar_aumento_km() {
        initComponents();
        NSS_instructor.setEditable(false);
        nombre_instructor.setEditable(false);
        generarDatosAutos();
        ((JSpinner.DefaultEditor) spnr_cantidad.getEditor())
        .getTextField().setEditable(false);
        
        
        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) spnr_cantidad.getEditor();

// Bloquear escritura
editor.getTextField().setEditable(false);

// Ajustar tamaño del campo interno
editor.getTextField().setColumns(4); 

// Ajustar tamaño externo del spinner
spnr_cantidad.setPreferredSize(new Dimension(80, 28));


    }
    
    public void llenar_instructor(){
        String matricula = campo_filtro.getText();
        Instructor i = new InstructorDAO().mostrarInstructorMatricula(matricula);
        if(i==null){
            NSS_instructor.setText("");
        nombre_instructor.setText("");
        }else{
        NSS_instructor.setText(i.getNSS());
        nombre_instructor.setText(i.getNombre());
        }
    }
    
    public boolean campoLleno(){
        if(campo_filtro.getText().length()==6){
            btn_guardar.setEnabled(true);
            llenar_instructor();
            
            return true;
        }else {
            btn_guardar.setEnabled(false);
            llenar_instructor();
            
            return false;
        }
    }
    
    
    public void generarDatosAutos() {

    // Convertir filtro a mayúsculas
    
    
    campo_filtro.setText(campo_filtro.getText().toUpperCase());

    String[] columnas = {"Matricula", "Modelo", "Marca", "Asignado", "Kilometraje"};

    // Obtener autos filtrados SOLO por matricula
        ArrayList<Auto> autosLista = new AutoDAO()
            .mostrarAutosFiltro("matricula", campo_filtro.getText());

    // Lista para llenar la tabla
    ArrayList<Object[]> autosParaMostrar = new ArrayList<>();

    for (Auto e : autosLista) {
        autosParaMostrar.add(new Object[]{
            e.getMatricula(),
            e.getModelo(),
            e.getMarca(),
            e.isAsignado(),
            e.getKilometraje()
        });
    }

    // Modelo sin edición
        DefaultTableModel modeloAutos =
            new DefaultTableModel(autosParaMostrar.toArray(new Object[0][]), columnas) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

    tabla_autos.setModel(modeloAutos);
    tabla_autos.setRowHeight(26);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        btn_cancelar = new javax.swing.JButton();
        spnr_cantidad = new javax.swing.JSpinner();
        txt_instructor = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JLabel();
        NSS_instructor = new javax.swing.JTextField();
        campo_filtro = new javax.swing.JTextField();
        nombre_instructor = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_aumento = new javax.swing.JLabel();
        txt_nss = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_autos = new javax.swing.JTable();

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        spnr_cantidad.setValue(0000);
        spnr_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spnr_cantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnr_cantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnr_cantidadKeyTyped(evt);
            }
        });

        txt_instructor.setText("Instructor a cargo");

        txt_matricula.setText("Matricula");

        NSS_instructor.setColumns(5);

        campo_filtro.setColumns(5);
        campo_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_filtroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_filtroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_filtroKeyTyped(evt);
            }
        });

        nombre_instructor.setColumns(5);

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_aumento.setText("Aumentar");

        txt_nss.setText("NSS");

        txt_nombre.setText("Nombre");

        tabla_autos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_autos);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_instructor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NSS_instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(txt_matricula)
                                .addGap(18, 18, 18)
                                .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(txt_aumento))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(txt_nss)))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombre)
                    .addComponent(nombre_instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnr_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_guardar))
                .addGap(70, 70, 70))
            .addComponent(jScrollPane1)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nss)
                            .addComponent(txt_nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NSS_instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_instructor)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_cancelar)))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_aumento)
                    .addComponent(spnr_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matricula)
                    .addComponent(btn_guardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyPressed
        // TODO add your handling code here:
        if(campoLleno() && evt.getKeyChar()!=8){
            evt.consume();
        }
        generarDatosAutos();
    }//GEN-LAST:event_campo_filtroKeyPressed

    private void campo_filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyReleased
        // TODO add your handling code here:
        if(campoLleno() && evt.getKeyChar()!=8){
            evt.consume();
        }
        generarDatosAutos();
    }//GEN-LAST:event_campo_filtroKeyReleased

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
                                                 

    // Validar instructor cargado
    if (NSS_instructor.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró un instructor asignado a la matrícula.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtener datos
    String matricula = campo_filtro.getText();
    int cantidad = (Integer) spnr_cantidad.getValue();

    // Validar cantidad
    if (cantidad <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "La cantidad de kilómetros debe ser mayor a 0.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Llamar procedimiento
    boolean ok = new ProceduresDAO()
            .registrarIncrementoKilometraje(matricula, cantidad);

    if (ok) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Kilometraje actualizado correctamente.");

        generarDatosAutos(); // refrescar tabla
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Error al registrar el kilometraje.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }


        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void campo_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyTyped
        // TODO add your handling code here:
        if(campoLleno() && evt.getKeyChar()!=8){
            evt.consume();
        }
        generarDatosAutos();
    }//GEN-LAST:event_campo_filtroKeyTyped

    private void spnr_cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnr_cantidadKeyPressed
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_spnr_cantidadKeyPressed

    private void spnr_cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnr_cantidadKeyReleased
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_spnr_cantidadKeyReleased

    private void spnr_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnr_cantidadKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_spnr_cantidadKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NSS_instructor;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JTextField campo_filtro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre_instructor;
    private javax.swing.JPanel panel;
    private javax.swing.JSpinner spnr_cantidad;
    private javax.swing.JTable tabla_autos;
    private javax.swing.JLabel txt_aumento;
    private javax.swing.JLabel txt_instructor;
    private javax.swing.JLabel txt_matricula;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_nss;
    // End of variables declaration//GEN-END:variables
}
