/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.ViewsDAO;
import Modelos.Historial;
import java.util.ArrayList;
import javax.swing.JScrollPane;

/**
 *
 * @author Usuario
 */
public class IF_view_historial extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_view_historial
     */
    JScrollPane sp;
    
    public IF_view_historial(JScrollPane sp) {
        initComponents();
        this.sp = sp;
        generarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_historial = new javax.swing.JTable();
        btn_regresar = new javax.swing.JButton();
        campo_filtro = new javax.swing.JTextField();
        txt_filtro = new javax.swing.JLabel();

        tabla_historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_historial);

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        campo_filtro.setColumns(15);
        campo_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_filtroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_filtroKeyReleased(evt);
            }
        });

        txt_filtro.setText("Filtrar por instructor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_regresar)
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_filtro)
                    .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_regresar)
                    .addComponent(txt_filtro))
                .addGap(7, 7, 7)
                .addComponent(campo_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        IF_inicio IF = new IF_inicio(sp);
        sp.add(IF);
         IF.setSize(sp.getWidth(), sp.getHeight());
         IF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void campo_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyPressed
        // TODO add your handling code here:
        generarTabla();
    }//GEN-LAST:event_campo_filtroKeyPressed

    private void campo_filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_filtroKeyReleased
        // TODO add your handling code here:
        generarTabla();
    }//GEN-LAST:event_campo_filtroKeyReleased

    private void generarTabla() {

        ArrayList<Historial> lista = new ViewsDAO().obtenerVistaHistorialCompletoFiltro(campo_filtro.getText());
        
    String[] columnas = {
        "ID", "Fecha Cambio", "NSS", "Nombre Completo",
        "Vehículo Anterior", "Marca Anterior", "Modelo Anterior",
        "Vehículo Nuevo", "Marca Nueva", "Modelo Nuevo"
    };

    javax.swing.table.DefaultTableModel modelo =
            new javax.swing.table.DefaultTableModel(null, columnas) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // No permitir edición
        }
    };

    for (Historial h : lista) {

        String nombreCompleto = h.getNombre() + " " +
                                h.getApellidopaterno() + " " +
                                h.getApellidomaterno();

        Object[] fila = new Object[]{
            h.getId(),
            h.getFecha_cambio(),
            h.getNss(),
            nombreCompleto,
            h.getVehiculo_anterior(),
            h.getMarca_anterior(),
            h.getModelo_anterior(),
            h.getVehiculo_nuevo(),
            h.getMarca_nueva(),
            h.getModelo_nueva()
        };

        modelo.addRow(fila);
    }

    tabla_historial.setModel(modelo);
    tabla_historial.setRowHeight(28);
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JTextField campo_filtro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_historial;
    private javax.swing.JLabel txt_filtro;
    // End of variables declaration//GEN-END:variables
}
