/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.ViewsDAO;
import Modelos.Instructor_Auto;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class IF_view_instructor_auto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_view_instructor_auto
     */
    JScrollPane sp;
    public IF_view_instructor_auto(JScrollPane sp) {
        initComponents();
        this.sp = sp;
        rb_instructor.setSelected(true);
        generarVistaInstructorAuto();
        filtro_instructor_auto.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            generarVistaInstructorAuto();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_isntructor_autos = new javax.swing.JTable();
        filtro_instructor_auto = new javax.swing.JTextField();
        rb_instructor = new javax.swing.JRadioButton();
        rb_auto = new javax.swing.JRadioButton();
        txt_filtro = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();

        tabla_isntructor_autos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_isntructor_autos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );

        filtro_instructor_auto.setColumns(15);
        filtro_instructor_auto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtro_instructor_autoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtro_instructor_autoKeyReleased(evt);
            }
        });

        buttonGroup1.add(rb_instructor);
        rb_instructor.setText("NSS instructor");
        rb_instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_instructorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_auto);
        rb_auto.setText("Matricula auto");
        rb_auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_autoActionPerformed(evt);
            }
        });

        txt_filtro.setText("Filtrar por:");

        btn_cerrar.setText("Regresar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_cerrar)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(filtro_instructor_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_filtro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_instructor)
                        .addGap(18, 18, 18)
                        .addComponent(rb_auto)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_instructor)
                    .addComponent(rb_auto)
                    .addComponent(txt_filtro)
                    .addComponent(btn_cerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtro_instructor_auto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        
        IF_inicio IF = new IF_inicio(sp);
        sp.add(IF);
         IF.setSize(sp.getWidth(), sp.getHeight());
         IF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void filtro_instructor_autoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtro_instructor_autoKeyReleased
        // TODO add your handling code here:
        generarVistaInstructorAuto();
    }//GEN-LAST:event_filtro_instructor_autoKeyReleased

    private void filtro_instructor_autoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtro_instructor_autoKeyPressed
        // TODO add your handling code here:
        generarVistaInstructorAuto();
    }//GEN-LAST:event_filtro_instructor_autoKeyPressed

    private void rb_instructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_instructorActionPerformed
        // TODO add your handling code here:
        generarVistaInstructorAuto();
    }//GEN-LAST:event_rb_instructorActionPerformed

    private void rb_autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_autoActionPerformed
        // TODO add your handling code here:
        generarVistaInstructorAuto();
    }//GEN-LAST:event_rb_autoActionPerformed

    
    
    public void generarVistaInstructorAuto() {

        String tipo;
        if(rb_auto.isSelected())
            tipo = "matricula";
        else
            tipo = "nss";
        
        String filtro = filtro_instructor_auto.getText();
    // Encabezados de la tabla
    String[] columnas = {
        "NSS", "Nombre", "Apellido P.", "Apellido M.", "Senior",
        "Matrícula Auto", "Marca", "Modelo", "Kilometraje", "Asignado"
    };

    // Obtener la lista desde el DAO
        ArrayList<Instructor_Auto> lista = new ViewsDAO().obtenerVistaInstructorAutoFiltro(tipo, filtro);

    // Convertir a un arreglo bidimensional para la tabla
    ArrayList<Object[]> datosTabla = new ArrayList<>();

    for (Instructor_Auto v : lista) {
        datosTabla.add(new Object[]{
            v.getNss(),
            v.getNombre(),
            v.getApellidopaterno(),
            v.getApellidomaterno(),
            v.isSenior(),
            v.getAuto_matricula(),
            v.getMarca(),
            v.getModelo(),
            v.getKilometraje(),
            v.isAsignado()
        });
    }

    // Crear el modelo de la tabla (solo lectura)
        DefaultTableModel modelo = new DefaultTableModel(
            datosTabla.toArray(new Object[0][]),
            columnas
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;   // ninguna celda editable
        }
    };

    tabla_isntructor_autos.setModel(modelo);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField filtro_instructor_auto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_auto;
    private javax.swing.JRadioButton rb_instructor;
    private javax.swing.JTable tabla_isntructor_autos;
    private javax.swing.JLabel txt_filtro;
    // End of variables declaration//GEN-END:variables
}
